// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBddI82ubgfapgOr8eR5lwtd-rp4yY8q4Y',
    appId: '1:338735247031:web:ee0f4005fe425c689e2732',
    messagingSenderId: '338735247031',
    projectId: 'smart-city-guide-4b29b',
    authDomain: 'smart-city-guide-4b29b.firebaseapp.com',
    storageBucket: 'smart-city-guide-4b29b.firebasestorage.app',
    measurementId: 'G-JM1DE2KP12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5aYnggkKnFNUqBL8cskM2LowBi6s-Vsg',
    appId: '1:338735247031:android:daaea0ae7921950a9e2732',
    messagingSenderId: '338735247031',
    projectId: 'smart-city-guide-4b29b',
    storageBucket: 'smart-city-guide-4b29b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbCV5o7GdusatXewWfhBSOhNLmDRpT0Lo',
    appId: '1:338735247031:ios:3a3eaa04d14de0e09e2732',
    messagingSenderId: '338735247031',
    projectId: 'smart-city-guide-4b29b',
    storageBucket: 'smart-city-guide-4b29b.firebasestorage.app',
    androidClientId: '338735247031-j7ujvm7soa95ou9lblv8knni4t6bg56l.apps.googleusercontent.com',
    iosClientId: '338735247031-1vdfm20i0e8c0pnscr9bhj8ae2kllp20.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbCV5o7GdusatXewWfhBSOhNLmDRpT0Lo',
    appId: '1:338735247031:ios:3a3eaa04d14de0e09e2732',
    messagingSenderId: '338735247031',
    projectId: 'smart-city-guide-4b29b',
    storageBucket: 'smart-city-guide-4b29b.firebasestorage.app',
    androidClientId: '338735247031-j7ujvm7soa95ou9lblv8knni4t6bg56l.apps.googleusercontent.com',
    iosClientId: '338735247031-1vdfm20i0e8c0pnscr9bhj8ae2kllp20.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBddI82ubgfapgOr8eR5lwtd-rp4yY8q4Y',
    appId: '1:338735247031:web:c14e0a594183f6fb9e2732',
    messagingSenderId: '338735247031',
    projectId: 'smart-city-guide-4b29b',
    authDomain: 'smart-city-guide-4b29b.firebaseapp.com',
    storageBucket: 'smart-city-guide-4b29b.firebasestorage.app',
    measurementId: 'G-VPYSNEQX5C',
  );

}